variables: !include GN3V00/variables-ghost.yaml
global_cuts: !include splits/simple-split.yaml

ttbar: &ttbar
  name: ttbar
  equal_jets: False
  pattern:
    - "user.wlai.601589.e8547_s3797_r13144_p6368.tdd.GN3_dev.25_2_27.24-11-10_GN3v00_output.h5/*.h5" # mc20d
    - "user.wlai.601589.e8549_s4159_r14799_p6368.tdd.GN3_dev.25_2_27.24-11-10_GN3v00_output.h5/*.h5" # mc23a
    - "user.wlai.601589.e8549_s4162_r14622_p6368.tdd.GN3_dev.25_2_27.24-11-10_GN3v00_output.h5/*.h5" # mc23c

zprime: &zprime
  name: zprime
  equal_jets: False
  pattern:
    - "user.wlai.800030.e7954_s3681_r13144_p6368.tdd.GN3_dev.25_2_27.24-11-10_GN3v00_output.h5/*.h5" # mc20d
    - "user.wlai.800030.e7954_s3797_r13144_p6368.tdd.GN3_dev.25_2_27.24-11-10_GN3v00_output.h5/*.h5" # mc20d
    - "user.wlai.800030.e8514_s4162_r14622_p6368.tdd.GN3_dev.25_2_27.24-11-14_GN3v00_output.h5/*.h5" # mc23a

lowpt: &lowpt
  name: lowpt
  cuts:
    - [pt_btagJes, ">", 20_000]
    - [pt_btagJes, "<", 250_000]
highpt: &highpt
  name: highpt
  cuts:
    - [pt_btagJes, ">", 250_000]
    - [pt_btagJes, "<", 6_000_000]

components:
  - region:
      <<: *lowpt
    sample:
      <<: *ttbar
    flavours: [ghostsplitbjets]
    num_jets: 79_000_000
    num_jets_test: 2_000_000

  - region:
      <<: *lowpt
    sample:
      <<: *ttbar
    flavours: [ghostsplitcjets]
    num_jets: 26_500_000
    num_jets_test: 2_000_000

  - region:
      <<: *lowpt
    sample:
      <<: *ttbar
    flavours: [ghostsplitsjets]
    num_jets: 21_000_000
    num_jets_test: 1_000_000

  - region:
      <<: *lowpt
    sample:
      <<: *ttbar
    flavours: [ghostsplitudjets]
    num_jets: 54_000_000
    num_jets_test: 1_000_000

  - region:
      <<: *lowpt
    sample:
      <<: *ttbar
    flavours: [ghostsplitgjets]
    num_jets: 46_000_000
    num_jets_test: 1_000_000

  - region:
      <<: *lowpt
    sample:
      <<: *ttbar
    flavours: [ghostsplittaujets]
    num_jets: 9_000_000
    num_jets_test: 500_000

  - region:
      <<: *highpt
    sample:
      <<: *zprime
    flavours: [ghostsplitbjets]
    num_jets: 39_500_000
    num_jets_test: 2_000_000

  - region:
      <<: *highpt
    sample:
      <<: *zprime
    flavours: [ghostsplitcjets]
    num_jets: 13_250_000
    num_jets_test: 2_000_000

  - region:
      <<: *highpt
    sample:
      <<: *zprime
    flavours: [ghostsplitsjets]
    num_jets: 10_500_000
    num_jets_test: 1_000_000

  - region:
      <<: *highpt
    sample:
      <<: *zprime
    flavours: [ghostsplitudjets]
    num_jets: 27_000_000
    num_jets_test: 1_000_000

  - region:
      <<: *highpt
    sample:
      <<: *zprime
    flavours: [ghostsplitgjets]
    num_jets: 23_000_000
    num_jets_test: 1_000_000

  - region:
      <<: *highpt
    sample:
      <<: *zprime
    flavours: [ghostsplittaujets]
    num_jets: 4_500_000
    num_jets_test: 200_000

resampling:
  target: ghostsplitcjets
  method: countup
  sampling_fraction: 1
  variables:
    pt_btagJes:
      bins: [[20_000, 250_000, 20], [250_000, 1_000_000, 20], [1_000_000, 6_000_000, 20]]
    absEta_btagJes:
      bins: [[0, 2.5, 10]]

# note: sensible defaults are defined in the PreprocessingConfig constructor
global:
  jets_name: jets
  batch_size: 1_000_000
  num_jets_estimate: 25_000_000
  base_dir: /unix/atlas2/weilai/datasets/atlas/upp_outs/ghost_high_stat_full
  ntuple_dir: /unix/atlas2/weilai/datasets/atlas/ntuples/gn3v00
